apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
spec:
  selector:
    matchLabels:
      app: influxdb-app
  template:
    metadata:
      labels:
        app: influxdb-app
    spec:
      containers:
      - name: influxdb-container
        image: x_influxdb
        imagePullPolicy: Never
        volumeMounts:
          - name: influxdb-volume
            mountPath: /var/lib/influxdb

        ports:
        - containerPort: 8086
      volumes:
        - name: influxdb-volume
          persistentVolumeClaim:
            claimName: influxdb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
spec:
  selector:
    app: influxdb-app
  clusterIP: 10.99.99.100
  type: ClusterIP
  ports:
  - port: 8086
    targetPort: 8086
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pvc
spec:
  resources:
    requests:
      storage: 300Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce


