apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql-app
  template:
    metadata:
      labels:
        app: mysql-app
    spec:
      containers:
      - name: mysql-container
        image: x_mysql
        imagePullPolicy: Never
        volumeMounts:
          - name: mysql-volume
            mountPath: /var/lib/mysql
        ports:
        - containerPort: 3306
        livenessProbe:
          exec:
            command:
              - sh
              - /health.sh
          initialDelaySeconds: 30
          periodSeconds: 5
      volumes:
        - name: mysql-volume
          persistentVolumeClaim:
            claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql-app
  ports:
  - port: 3306
    targetPort: 3306
  type: ClusterIP
  clusterIP: 10.99.99.99
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  resources:
    requests:
      storage: 300Mi
  accessModes:
    - ReadWriteOnce
