apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pma-app
  template:
    metadata:
      labels:
        app: pma-app
    spec:
      containers:
      - name: pma-container
        image: x_phpmyadmin
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        livenessProbe:
          exec:
            command:
              - sh
              - /health.sh
          initialDelaySeconds: 30
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: pma-service
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: pma-app
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
