apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana-app
  template:
    metadata:
      labels:
        app: grafana-app
    spec:
      containers:
      - name: grafana-container
        image: x_grafana
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
          name: grafana
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: grafana-app
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
    name: grafana
